language: node_js
node_js:
  - '10'
cache:
  directories:
    - node_modules
script:
  - npm test -- --coverage
  - npm run build
after_script:
  - COVERALLS_REPO_TOKEN=$COVERALLS_REPO_TOKEN npm run coveralls
